spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/notice_management?useSSL=false&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  boot:
    admin:
      client:
        url: "http://localhost:8080"
#        instance:
#          service-url: "http://localhost:8000"

  application:
    name: message-chat

server:
  port: 8088
#  servlet:
#    context-path: /message

info:
  date: 2018/11/27 14:20
  author: Curtain

# 日志文件
logging:
  file: ./target/admin-server.log

#加载所有端点  默认只加载info、health
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    #关闭指定端点
#    shutdown:
#      enabled: false


